version : "3.0"

services:
    mongo:
        container_name: mongodb
        image: mongo
        restart: always
        volumes:
            - ./data:/data/mongo
        ports:
            - "27017:27017"
